//  User routes --------------------------------------------------------
###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "nombre": "Jhon",
    "apellido": "Travolta",
    "email": "correo1@asd.com",
    "contrasena": "123",
    "role_id": "1"
}

###
GET http://localhost:3000/api/users
Content-Type: application/json


###
GET http://localhost:3000/api/users/1
Content-Type: application/json

###
DELETE  http://localhost:3000/api/users/9
Content-Type: application/json

###
PUT http://localhost:3000/api/users/7
Content-Type: application/json

{
    "nombre": "Juan",
    "apellido": "CENA",
    "email": "corre@gmail.com",
    "contrasena": "123",
    "role_id": "1"
}

###
PUT http://localhost:3000/api/users/4
Content-Type: application/json

{
    "nombre": "Jorge",
    "apellido": "ALMUERZA",
    "email": "corre@gmail.com",
    "contrasena": "123",
    "role_id": "1"
}

###
PATCH  http://localhost:3000/api/users/4
Content-Type: application/json

{
    "nombre": "Pedro"
}


//  Auth routes  --------------------------------------------------------
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "correo1@asd.com",
    "contrasena": "123"
}

###
POST http://localhost:3000/api/auth/change-password/10
Content-Type: application/json

{
    "old_password": "123",
    "new_password": "12345",
    "confirm_password": "12345"
}


###
POST http://localhost:3000/api/auth/forgot-password/
Content-Type: application/json

{
    "email": "correo1@asd.com"
}

###
POST http://localhost:3000/api/auth/reset-password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTcyMDA2NjU3MSwiZXhwIjoxNzIwMDcwMTcxfQ.Xpe2NhCVxFs27zKOSftRP7RjvT_1Euu9j7-8kkok61s
Content-Type: application/json

{
    "nueva_contrasena": "123"
}

// Whatsapp -----------------------------------------------------

###
POST http://localhost:3000/api/whatsapp/send-message-whatsapp/
Content-Type: application/json

{
    "to": "543743562206",
    "appointmentDate": "20/85/54",
    "appointmentTime": "10:20",
    "dentist": "Dr. Smith"
}



// Email -----------------------------------------------------

###
POST http://localhost:3000/api/email/send-message-email/
Content-Type: application/json

{
    "to": "martinchoo_13@hotmail.com",
    "subject": "Prueba",
    "text": "Esto es texto de prueba" 
}